var sum = require( 'sum' );

var content = "";
content += "An article in the most recent issue of Scientific American Mind explores the emerging field of nutritional psychology and finds there is increased recognition of the relationship between diet and brain health. Although no singular food may improve mood or sharpen the mind, research suggests that diets from the Mediterranean, Scandinavia, and Japan may play a role in preserving psychological and cognitive well-being. Experiencing the benefits of such diets may require a change in eating habits--something the Japanese themselves know from their own experience. Acclaimed food historian Bee Wilson explains in her latest book, First Bite: How We Learn to Eat, 'Japan itself is in fact a model for how whole food environments can change in positive and unexpected ways.'\n"
content += "Using history, neuroscience, anthropology, psychology, and nutritional science, First Bite explores the origins of food habits and finds that they are influenced by a variety of factors, including gender, memory, culture. Since a large portion of taste preference is learned, it can also be re-learned by both individuals and countries. Japan is a nation now known for its culinary aesthetics and emphasis of umami. Despite the perception that Japan has always had an innate culinary culture, it was primarily seen as sustenance prior to the twentieth century. As Bee Wilson explains, a confluence of events shaped the cuisine typically considered as being quintessential to the country.\n"
content += "[T]he Japanese only really started eating what we think of as Japanese food in the years after World War II. During the war, Japan suffered some of the worst hunger in any of the nations involved in the war: out of 1.74 million military deaths from 1941 to 1945, as many as 1 million were due to starvation. Once again, the Japanese were reduced to acorns and rough grains and sparse amounts of rice, as they had been so often before. Japan was heavily dependent on imported food and was therefore hit especially hard when the war curtailed supplies. The ration rice—given in woefully inadequate quantities—became known as 'Five Color Rice': white rice, stale yellow rice, dried green beans, coarse red grains, and brown insects. Yet when the Japanese finally bounced back from hunger in the 1950s, they boomed to a state of unprecedented prosperity and gained a new openness to the pleasures of food.\n"
content += "Japan’s adventurousness about food was partly a consequence of American postwar food aid. In 1947, the occupying US forces brought in a new school lunch program to alleviate hunger among Japanese children. Before this, children would bring food from home: rice, a few pickles, maybe some bonito flakes (made of dried, fermented tuna), but almost nothing in the way of protein. Many children suffered constant runny noses from their inadequate diet. The new official American lunches guaranteed that every child would have milk and a white bread roll (made from US wheat) plus a hot dish, which was often some kind of stew made from the remaining stockpiles of canned food from the Japanese army, spiced with curry powder. The generation of Japanese children reared on these eclectic lunches grew into adults who were open to unusual flavor combinations. In the 1950s, as the national income doubled, people migrated from the land to tiny city apartments. Everyone aspired to buy the 'three sacred treasures': a TV, a washing machine, and a fridge. With new money came new ingredients, and the national diet shifted from carbohydrate to protein. As the Japanese food historian Naomiche Ishige has explained, once levels of food consumption rose again to prewar levels, 'it became clear that the Japanese were not returning to the dietary pattern of the past, but were rather in the process of creating new eating habits.'\n"
content += "In 1955 the average person in Japan ate just 3.4 eggs and 1.1 kilogram (2.4 pounds) of meat a year, but 110.7 kilograms (244 pounds) of rice; by 1978, rice consumption had markedly decreased, to 81 kilograms (178.6 pounds) per capita, while people were now eating 14.9 eggs and 8.7 kilograms (19.2 pounds) of pork alone, not to mention beef, chicken, and fi sh. But this wasn’t just about Japan moving from privation to plenty.\n"
content += "More than anything else, it was a shift from dislike to like. Where once it was seen as extravagant in Japan to serve more than one or two dishes to accompany the evening’s rice, now—thanks to the new affluence—it was becoming common to serve three or more dishes, plus rice, soup, and pickles. Newspapers published recipe columns for the first time, and after centuries of silence at the table, the Japanese started to talk with great discernment about food. They embraced foreign recipes, such as Korean barbecue, Western breaded prawns, and Chinese stir-fries, and made them so much their own that when foreigners came to Japan and tasted them, it seemed to be 'Japanese food.' Perhaps thanks to all those years of culinary isolation, when Japanese cooks encountered new Western foods, they did not adopt them wholesale, but adapted them to fit with traditional Japanese ideas about portion size and how a meal should be structured. When an omelet was served, for example, it probably did not have fried potatoes on the side as it might in the West, but the old miso soup, vegetables, and rice. At last, Japan had started eating the way we expect them to: choosily, pleasurably, and healthily.\n"
content += "There was nothing inevitable or innate in the Japanese spirit that gave them this near-ideal diet. Instead of being dispirited by the way the Japanese eat, we should be encouraged by it. Japan shows the extent to which food habits can evolve. We sometimes imagine that Italians are born loving pasta, or that French babies have a native understanding of globe artichokes that runs in their blood. The food scholar Elizabeth Rozin has spoken of the 'flavor principles' that flow through national cuisine, often changing very little for centuries, such as 'onions, lard and paprika' in Hungary or 'peanuts, peppers and tomatoes' in West Africa. 'It would be as unlikely,' Rozin writes, 'for a Chinese person to season his noodles with sour cream and dill as it would be for a Swede to flavor his herring with soy sauce and gingerroot.' Yet Japan shows that such unlikely things do happen. Flavor principles change. Diets change. And the people eating these diets also change.\n"
content += "It turns out that wherever they are from, people are capable of altering not just what they eat, but also what they want to eat, and their behavior when eating it. It is startling that Japan, a country whose 'flavor principles' included little spice except ginger, should fall in love with katsu curry sauce made with cumin, garlic, and chili. A country where people once ate meals in silence has shifted to one where food is obsessively discussed and noodles are loudly slurped to increase the enjoyment. So perhaps the real question should be: If the Japanese can change, why can’t we?\n"

var abstract = sum({ 'corpus': content, 'nSentences': 5 });
console.log(abstract.summary);
